//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoldatovaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merch()
        {
            this.OrderMerches = new HashSet<OrderMerch>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public int cost { get; set; }
        public Nullable<int> sale { get; set; }
        public string picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMerch> OrderMerches { get; set; }
    }
}
