//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoldatovaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merch()
        {
            this.OrderMerches = new HashSet<OrderMerch>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public int cost { get; set; }
        public Nullable<int> sale { get; set; }
        public string picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMerch> OrderMerches { get; set; }

        public Nullable<double> DiscountDec
        {
            get
            {
                return sale * 100;
            }
        }

        public string NewPrice
        {
            get
            {
                if (Convert.ToDouble(sale) != 0)
                {
                    return Convert.ToString(Convert.ToDouble(cost) - Convert.ToDouble(sale) * Convert.ToDouble(cost) / 100);
                }
                else return "";
            }
        }
        public bool IsSale
        {
            get
            {
                if (Convert.ToDouble(sale) != 0) return true;
                else return false;
            }
        }
        public string Strike
        {
            get
            {
                return IsSale ? "Strikethrough" : "None";
            }
        }
        public string Vis
        {
            get
            {
                return IsSale ? "Visible" : "Hidden";
            }
        }
        public string greenPart
        {
            get
            {
                return IsSale ? "YellowGreen" : "None";
            }
        }
    }
}
