//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoldatovaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMerch
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int MerchID { get; set; }
    
        public virtual Merch Merch { get; set; }
        public virtual Order Order { get; set; }
    }
}
