//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoldatovaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderMerches = new HashSet<OrderMerch>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateArrive { get; set; }
        public bool Arrived { get; set; }
        public int Place { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> MerchID { get; set; }
    
        public virtual Place Place1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMerch> OrderMerches { get; set; }
    }
}
