//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoldatovaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public string name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Entry { get; set; }
        public string Picture { get; set; }
    
        public virtual EntryType EntryType { get; set; }
        public virtual Role Role { get; set; }

    public string Dates
        {
            get
            {
                string[] times = Convert.ToString(Date).Split(new char[] { ' ' });
               string dates = times[0];
                return dates;
            }
        }

    }
}
